# The type of generator to be run
generator: collection

# The root directory of the recipes
recipes_root: recipes/

# The input plugins to be run for the generator
inputs:
  - name: text_file
    conf:
      path: input/sentinel2_ard/content.jsonl

# The output plugins to be run for the generator
outputs:
  - name: standard_out
# Output plugins can use mappings to reshape the output
    mappings:
      - name: stac
        conf:
          stac_version: '1.0.0'
          stac_extensions: []
          stac_root_url: 'https://api.stac.ceda.ac.uk'
  - name: text_file
    conf:
      filepath: ./outputs/sentinel2_ard_collection_raw.txt

failed_outputs:
  - name: standard_out
